### ISSUE TITLE
How to make cm12.1 for blade a1 based on your sources

### ISSUE THREAD

**Issue by mazige1997** [xen0n/android_device_zte_p635-common#1]
When I try to make cm12.1 for blade a1,I met this error:make: **\* No rule to make target `/data/android/system/out/target/product/p635b32/obj/KERNEL_OBJ/usr', needed by`/data/android/system/out/target/product/p635b32/obj_arm/SHARED_LIBRARIES/libtinycompress_intermediates/compress.o'.  Stop.

**Comment by xen0n** [comment]
Just `mkdir` the directory.

**Comment by mazige1997** [comment]
Thank you.
