### ISSUE TITLE
指纹支持建议

### ISSUE THREAD

**Issue by yifeng66** [xen0n/android_device_zte_p635-common#3]
wangxuerui先生您好，我发现[一个很好的开源项目](https://github.com/uccmawei/FingerprintIdentify)，如果把它合并到您的开源项目里可能会出现第一个a1cm12.1的指纹ROM，我是一个初学者，有很多还不会，请指出我的错误。

**Comment by xen0n** [comment]
* 指纹是平台级别功能，不一定非要用这个项目
* 实际上这项目并不好，开发习惯很差，比方说英语介绍都不懂什么意思（这种情况下就干脆直接写中文好了），又比如一个提交就一个版本出来了，具体有哪些变化都不好跟进
* **最重要的一点，不幸的是这个库运行在应用层，而ROM需要框架层支持。**

这是什么意思？直接引入这个库根本不可能，因为

* 你想用它支持手机的指纹功能，结果你忘了**我们在开发的就是ROM本身**
* 这个库完全靠间接向下访问到框架层API才能运行，问题在于**我们不支持指纹正是因为没有如同原厂ROM一般接好框架层API**
* 最终结果就是这个库根本编译都通不过

希望能通过以上解释，使你对ROM移植有一定的感性认识，须知**框架层开发和应用开发不是同一境界**

closing

**Comment by xen0n** [comment]
你的另一个错误是不会写issue，我帮你改了格式，下次不要把正文写进标题里面
